import mongoose from "mongoose";

const RegistrationDataSchema = new mongoose.Schema(
  {
    // ==========================================
    // Event
    // ==========================================

    eventId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Event",
      required: [true, "Event is required."],
      index: true,
    },

    // ==========================================
    // Registration Data Type
    // ==========================================

    regDataTypeId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "RegDataType",
      required: [true, "Reg data type is required."],
      index: true,
    },

    // ==========================================
    // Registration Information
    // ==========================================

    name: {
      type: String,
      required: [true, "Name is required."],
      trim: true,
      maxlength: 100,
    },

    // Generated by backend
    // Example: SPOT-001, SPOT-002, SPOT-003
    regNum: {
      type: String,
      required: [true, "Registration number is required."],
      trim: true,
    },

    // ==========================================
    // Optional Information
    // ==========================================

    email: {
      type: String,
      trim: true,
      lowercase: true,
    },

    mobile: {
      type: String,
      trim: true,
    },

    mciNumber: {
      type: String,
      trim: true,
    },

    address: {
      type: String,
      trim: true,
    },

    city: {
      type: String,
      trim: true,
    },

    state: {
      type: String,
      trim: true,
    },

    country: {
      type: String,
      trim: true,
    },

    reference: {
      type: String,
      trim: true,
    },

    note: {
      type: String,
      trim: true,
    },

    // for printing
    isPrinted: {
      type: Boolean,
      default: false,
    },

    printedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
  },
);

// ==========================================
// Indexes
// ==========================================

// Same registration number can exist in
// different events, but cannot be duplicated
// inside the same event.
RegistrationDataSchema.index(
  {
    eventId: 1,
    regNum: 1,
  },
  {
    unique: true,
  },
);

RegistrationDataSchema.index({
  createdAt: -1,
});

// ==========================================
// JSON Transform
// ==========================================

RegistrationDataSchema.set("toJSON", {
  transform(doc, ret) {
    delete ret.__v;

    return ret;
  },
});

// ==========================================
// Export
// ==========================================

const RegistrationData =
  mongoose.models.RegistrationData ||
  mongoose.model("RegistrationData", RegistrationDataSchema);

export default RegistrationData;
